backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
collections:
  - name: game_docs
    label: Game Docs
    folder: src/routes/tov/gamedocs
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: doc_navigations
    label: Document Navigations
    folder: static/navs
    format: json
    create: true
    fields:
      - label: Categories
        label_singular: a new category
        name: categories
        widget: list
        allow_add: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: Articles
            label_singular: an article route
            name: articles
            widget: list
            allow_add: true
            fields:
              - label: Article
                name: article
                widget: relation
                collection: game_docs
                value_field: title
                search_fields: [title]


media_folder: "static/uploads"
public_folder: "/uploads"
