backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
collections:
  - name: game_docs
    label: Game Docs
    folder: src/routes/tov/gamedocs
    preview_path: tov/gamedocs/{{filename}}
    create: true
    identifier_field: identifier
    fields:
      - {label: "Identifier (filename)", name: "identifier", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: doc_navigations
    label: Document Navigations
    folder: src/lib/navs
    format: json
    fields:
      - label: Categories
        label_singular: a new category
        name: categories
        widget: list
        allow_add: true
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: Articles
            label_singular: an article route
            name: articles
            widget: list
            allow_add: true
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: Article
                name: article_identifier
                widget: relation
                collection: game_docs
                value_field: identifier
                search_fields: [title, identifier]


media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://verrpg.com
display_url: https://verrpg.com
